os:
    - linux
language: node_js
before_install:
    - stty cols 80
install:
    - npm ci
node_js:
    - '10'
branches:
    only:
        - develop
cache:
    directories:
        - node_modules
        - '$HOME/.npm'
addons:
    browserstack:
        username: vincentogloblins1
        forcelocal: true
        access_key:
            secure: WrPHo6phISBwFv1DbhH1bh7M27mBECE8685JaoScjNWXml8qV8Xg6R2mGpzP0ZyJk4P7HL70HCyCe7EbLxKrrKtVD6A1Uk/7q1gP9/pdJYtgaRXpbSyAN9r9/lwn9pKR0aZqFViq3DPdrWD++gaU/xOOjOYAtPZv7150TiJ+/IlbMus4NwVKMnRCK27feU4KIHIH+6+JhOLq/Tq7NR1StX/cL2wkimgQM17AIKs4bw7Bq/pjYonut9F85o4YGsy116t8h2m+n/xHXa/QS4YJXyyd7t0YoJtBgEnv79FzzgWR33D3OGBQ+0wyfCL/vc7bFCSKdO2Nb6befaUxX+XMK488ElagGTNmL8wXizSoj+qvSwO6jLtf99LsJo1zL4jJyScij5LcbZkbmFSVBuY2C2p7KkVJRCqALvqv8Cv5ecw+UHtvoBkGhBt6WPNJdK2C1Jk6MV69IGUmD3KKESJWgox+JDc+iqyV6XLS4L9UpPutWRQytyk74ydlOUSxUJ0AEPMY6CGzsXgmgJCx+iyoyLC+SrKd84Bu/0zL3Lcq87ZHcGEIxJBseC86Gtgsz8PQrB5rzlumkLnfP7a5n5HUkB9XjwusRsiOnFqm6WGsd7UooinJ9CXlr+sXAmWHvrVLr0iilSJ6kkOcWDBQRRAHGhSuoVOnyI44sM0KA7uo5DI=
script:
    - echo '0. Global test'
    - npm run test
    - echo '1. Browserstack tests'
    - npm run badges.test.e2e.remote
    - echo '2. Generate documentation'
    - npm run build-storybook
    - echo '3. Deploy documentation'
    - bash ./deploy.sh
env:
    global:
        - GH_REF: github.com/vogloblinsky/nutrition-web-components.git
        - secure: RWkvzXuFIk8u4jIfjLYMR+qe0ySvL0788MKb07wSYxya4MSNfAKf8KJs7JRIfAVFllfLZD0OjUgjAyBm7RpkXCKHoC6ePInQslZoHTKXgohINuOX1sVb5GTY9XnaAIzhRlLjz/1e9aoQ+MAIg890t8YnZzEg5dl9EgWQc78ufU627IG1o4L609T1CboRGgJAgss7khM3z+7SonaZCSDxvfmFC5Ri4ZhEs2GxhJUyo8+eFiZ+B5Uzt1yVX9WsaQ5ylg6mzTjm16164HxdMHgubDaHGv6VaYyJ2U31e5DDo21WPGVI+sp9jeXQUm/GthzxDGa/g175cib9Es6QcuQ7h/LJl4ku37vIuwJcTJ4Hk8u5nUZN+R/C59IOh/BNpWqdcACdbP5p+lTWmEEh/F4Dub1NUMA0/CXhQg9nUYhy8eaHu+GX+2LBSxZ9VNaMeQmLRygfVKgnZ1nC65JcJAW21J0fbvOBS3zRc90KyeG/ridNzpTYeAsDhphN59iN1NC1citu5wN7KqrgmS/E2lJsh/BHqg4+LU0VCqUO5xUEqUy7cq9FVfEMxkm8Oj+Ae08gDlemwYcAAvTmDZ4lroi0Ecm1FHet53+3YWkVvEtGLE8gHMsg8sncBKkIXVHrVKVSlTy6gh/PSl2vAixPVdgTes84ebYpeUveIy2lyYbWmI0=
