os:
    - linux
language: node_js
before_install:
    - stty cols 80
install:
    - npm ci
node_js: 'stable'
branches:
    only:
        - develop
cache:
    directories:
        - node_modules
        - '$HOME/.npm'
script:
    - echo '0. Global test'
    - npm run test
    - echo '1. Saucelabs test'
    - npm run testsaucelabs
