os:
    - linux
language: node_js
install:
    - npm ci
node_js:
    - '10'
branches:
    only:
        - develop
cache:
    directories:
        - node_modules
        - '$HOME/.npm'
script:
    - echo '0. Global test'
    - npm run test
