os:
    - linux
language: node_js
before_install:
    - stty cols 80
install:
    - npm ci
node_js:
    - '10'
branches:
    only:
        - develop
cache:
    directories:
        - node_modules
        - '$HOME/.npm'
addons:
    sauce_connect: true
script:
    - echo '0. Global test'
    - npm run test
    - echo '1. Browserstack test'
    - npm run testcafe:browserstack
